import 'package:flutter/material.dart';
import 'package:prototype25/utils/models/call_model.dart';

import 'package:flutter/material.dart';
import 'package:prototype25/utils/models/call_model.dart';

final List<Call> calls = [
  Call(
    name: 'Sarah Miller',
    detail: 'Missed Voice Call',
    time: DateTime(2024, 2, 20, 15, 45).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.missed,
    isVideo: false,
  ),
  Call(
    name: 'John Davis',
    detail: 'Incoming Video Call',
    time: DateTime(2024, 2, 20, 14, 30).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.incoming,
    isVideo: true,
  ),
  Call(
    name: 'Team Meeting',
    detail: 'Outgoing Video Call',
    time: DateTime(2024, 2, 20, 10, 0).toIso8601String(),
    avatar: Icons.group,
    callType: CallType.outgoing,
    isVideo: true,
  ),
  Call(
    name: 'Michael Smith',
    detail: 'Outgoing Voice Call',
    time: DateTime(2024, 2, 19, 18, 0).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.outgoing,
    isVideo: false,
  ),
  Call(
    name: 'Alice Brown',
    detail: 'Missed Video Call',
    time: DateTime(2024, 2, 19, 16, 20).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.missed,
    isVideo: true,
  ),
  Call(
    name: 'David Wilson',
    detail: 'Incoming Voice Call',
    time: DateTime(2024, 2, 19, 13, 30).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.incoming,
    isVideo: false,
  ),
  Call(
    name: 'Project Team',
    detail: 'Outgoing Video Call',
    time: DateTime(2024, 2, 19, 10, 15).toIso8601String(),
    avatar: Icons.group,
    callType: CallType.outgoing,
    isVideo: true,
  ),
  Call(
    name: 'Emma Johnson',
    detail: 'Missed Voice Call',
    time: DateTime(2024, 2, 20, 9, 0).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.missed,
    isVideo: false,
  ),
  Call(
    name: 'Chris Evans',
    detail: 'Incoming Video Call',
    time: DateTime(2024, 2, 20, 8, 45).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.incoming,
    isVideo: true,
  ),
  Call(
    name: 'Marketing Team',
    detail: 'Outgoing Voice Call',
    time: DateTime(2024, 2, 19, 19, 30).toIso8601String(),
    avatar: Icons.group,
    callType: CallType.outgoing,
    isVideo: false,
  ),
  Call(
    name: 'Sophia Green',
    detail: 'Missed Video Call',
    time: DateTime(2024, 2, 19, 17, 15).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.missed,
    isVideo: true,
  ),
  Call(
    name: 'Liam Wright',
    detail: 'Incoming Voice Call',
    time: DateTime(2024, 2, 20, 15, 20).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.incoming,
    isVideo: false,
  ),
  Call(
    name: 'Olivia Martinez',
    detail: 'Outgoing Video Call',
    time: DateTime(2024, 2, 20, 14, 0).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.outgoing,
    isVideo: true,
  ),
  Call(
    name: 'Lucas Perez',
    detail: 'Missed Voice Call',
    time: DateTime(2024, 2, 20, 11, 50).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.missed,
    isVideo: false,
  ),
  Call(
    name: 'Charlotte Taylor',
    detail: 'Incoming Video Call',
    time: DateTime(2024, 2, 20, 10, 30).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.incoming,
    isVideo: true,
  ),
  Call(
    name: 'Engineering Team',
    detail: 'Outgoing Voice Call',
    time: DateTime(2024, 2, 19, 18, 45).toIso8601String(),
    avatar: Icons.group,
    callType: CallType.outgoing,
    isVideo: false,
  ),
  Call(
    name: 'Harper Lee',
    detail: 'Missed Video Call',
    time: DateTime(2024, 2, 20, 12, 10).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.missed,
    isVideo: true,
  ),
  Call(
    name: 'Ethan Harris',
    detail: 'Incoming Voice Call',
    time: DateTime(2024, 2, 19, 15, 0).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.incoming,
    isVideo: false,
  ),
  Call(
    name: 'Ava Young',
    detail: 'Outgoing Video Call',
    time: DateTime(2024, 2, 20, 16, 30).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.outgoing,
    isVideo: true,
  ),
  Call(
    name: 'Mason King',
    detail: 'Missed Voice Call',
    time: DateTime(2024, 2, 20, 13, 40).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.missed,
    isVideo: false,
  ),
  Call(
    name: 'Evelyn Scott',
    detail: 'Incoming Video Call',
    time: DateTime(2024, 2, 20, 9, 50).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.incoming,
    isVideo: true,
  ),
  Call(
    name: 'Benjamin Allen',
    detail: 'Outgoing Voice Call',
    time: DateTime(2024, 2, 19, 7, 20).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.outgoing,
    isVideo: false,
  ),
  Call(
    name: 'Abigail Moore',
    detail: 'Missed Video Call',
    time: DateTime(2024, 2, 19, 14, 10).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.missed,
    isVideo: true,
  ),
  Call(
    name: 'Henry Thomas',
    detail: 'Incoming Voice Call',
    time: DateTime(2024, 2, 20, 18, 30).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.incoming,
    isVideo: false,
  ),
  Call(
    name: 'Ella White',
    detail: 'Outgoing Video Call',
    time: DateTime(2024, 2, 20, 8, 30).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.outgoing,
    isVideo: true,
  ),
  Call(
    name: 'Alexander Clark',
    detail: 'Missed Voice Call',
    time: DateTime(2024, 2, 19, 17, 40).toIso8601String(),
    avatar: Icons.person,
    callType: CallType.missed,
    isVideo: false,
  ),
];
