import 'package:flutter/material.dart';
import 'package:prototype25/utils/models/chats_list_model.dart';

final List<Chat> chats = [
  Chat(
    name: 'Sarah Wilson',
    lastMessage: 'Hey, are we still meeting today?',
    time: DateTime(2024, 2, 20, 9, 45).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 0,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "I love making plans and trying new restaurants!",
  ),
  Chat(
    name: 'Design Team',
    lastMessage: 'New project updates available...',
    time: DateTime(2024, 2, 20, 11, 20).toIso8601String(),
    avatar: Icons.group,
    unreadCount: 3,
    profilePic: 'assets/images/dummy_group.png',
    aboutYou: "We bring creative ideas to life through teamwork!",
  ),
  Chat(
    name: 'John Smith',
    lastMessage: 'Thanks for the help!',
    time: DateTime(2024, 2, 19, 17, 30).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 0,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "Always up for a good chat and catching up on life.",
  ),
  Chat(
    name: 'Emily Davis',
    lastMessage: 'Check out this link!',
    time: DateTime(2024, 2, 20, 8, 30).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 2,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "I enjoy sharing cool articles and discoveries!",
  ),
  Chat(
    name: 'Marketing Team',
    lastMessage: 'Presentation scheduled for tomorrow.',
    time: DateTime(2024, 2, 20, 7, 15).toIso8601String(),
    avatar: Icons.group,
    unreadCount: 5,
    profilePic: 'assets/images/dummy_group.png',
    aboutYou: "We drive branding and innovative campaigns.",
  ),
  Chat(
    name: 'James Brown',
    lastMessage: 'See you at the gym.',
    time: DateTime(2024, 2, 19, 18, 0).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 1,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "Fitness enthusiast who never skips leg day!",
  ),
  Chat(
    name: 'Chris Taylor',
    lastMessage: 'Let me know your thoughts.',
    time: DateTime(2024, 2, 18, 14, 45).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 0,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "Detail-oriented and always ready to collaborate!",
  ),
  Chat(
    name: 'Tech Support',
    lastMessage: 'Your ticket has been resolved.',
    time: DateTime(2024, 2, 20, 14, 0).toIso8601String(),
    avatar: Icons.support_agent,
    unreadCount: 0,
    profilePic: 'assets/images/dummy_support.png',
    aboutYou: "Helping you solve tech problems, one issue at a time!",
  ),
  Chat(
    name: 'Anna Johnson',
    lastMessage: 'Can we talk now?',
    time: DateTime(2024, 2, 20, 10, 45).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 4,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "Creative mind stuck on design ideas more often than not!",
  ),
  Chat(
    name: 'David Martinez',
    lastMessage: 'Happy Birthday!',
    time: DateTime(2024, 2, 18, 10, 30).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 0,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "Never forgets birthdays and loves celebrating friends.",
  ),
  Chat(
    name: 'HR Department',
    lastMessage: 'Monthly updates shared.',
    time: DateTime(2024, 2, 16, 9, 0).toIso8601String(),
    avatar: Icons.business,
    unreadCount: 1,
    profilePic: 'assets/images/dummy_business.png',
    aboutYou: "Ensuring smooth operations and keeping employees informed.",
  ),
  Chat(
    name: 'Lisa Moore',
    lastMessage: 'Meeting rescheduled to 3 PM.',
    time: DateTime(2024, 2, 19, 15, 0).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 0,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "Organized and efficient—let’s keep things on schedule!",
  ),
  Chat(
    name: 'Adam Scott',
    lastMessage: 'Good morning!',
    time: DateTime(2024, 2, 20, 7, 30).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 2,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "Work hard, but always make time for coffee and friends.",
  ),
  Chat(
    name: 'Family Group',
    lastMessage: 'Dinner at 7 PM.',
    time: DateTime(2024, 2, 20, 18, 0).toIso8601String(),
    avatar: Icons.group,
    unreadCount: 6,
    profilePic: 'assets/images/dummy_group.png',
    aboutYou: "Family first, always checking in and planning meetups!",
  ),
  Chat(
    name: 'Sophia Lee',
    lastMessage: 'See you soon!',
    time: DateTime(2024, 2, 20, 16, 15).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 0,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "A perfectionist when it comes to work and presentations.",
  ),
  Chat(
    name: 'Daniel King',
    lastMessage: 'Don’t forget the deadline.',
    time: DateTime(2024, 2, 19, 12, 30).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 1,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "Deadlines matter! Let me know if you need help staying on track.",
  ),
  Chat(
    name: 'Gaming Buddies',
    lastMessage: 'Let’s play tonight!',
    time: DateTime(2024, 2, 20, 20, 0).toIso8601String(),
    avatar: Icons.group,
    unreadCount: 4,
    profilePic: 'assets/images/dummy_group.png',
    aboutYou: "Gaming marathons and late-night strategies are our thing!",
  ),
  Chat(
    name: 'Mom',
    lastMessage: 'Call me when you’re free.',
    time: DateTime(2024, 2, 20, 9, 0).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 1,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "Just making sure you’re eating well and taking care of yourself!",
  ),
  Chat(
    name: 'Tom Wilson',
    lastMessage: 'Great job on the project!',
    time: DateTime(2024, 2, 16, 15, 30).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 0,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "Supportive friend who loves celebrating achievements!",
  ),
  Chat(
    name: 'Rachel Green',
    lastMessage: 'Can you send me the notes?',
    time: DateTime(2024, 2, 17, 14, 15).toIso8601String(),
    avatar: Icons.person,
    unreadCount: 0,
    profilePic: 'assets/images/dummy_profile.png',
    aboutYou: "Always taking notes and making sure everyone is prepared!",
  ),
];
