import 'package:prototype25/utils/models/chat_history_model.dart';
import 'package:prototype25/utils/models/message_model.dart';

final Map<String, ChatHistory> dummyChats = {
  'Sarah Wilson': ChatHistory(
    aboutYou: "I love making plans and trying new restaurants!",
    messages: [
      Message(sender: 'friend', text: 'Hey, are we still meeting today?'),
      Message(sender: 'me', text: 'Yes, I’ll be there at 5 PM.'),
      Message(sender: 'friend', text: 'Great! Looking forward to it.'),
      Message(sender: 'me', text: 'Do you want to grab dinner after?'),
      Message(sender: 'friend', text: 'Sure, that sounds great!'),
      Message(sender: 'me', text: 'Any preferences for the restaurant?'),
      Message(sender: 'friend', text: 'How about that new Italian place?'),
      Message(sender: 'me', text: 'Perfect, I’ve been wanting to try it.'),
      Message(sender: 'friend', text: 'Same here! See you at 5.'),
      Message(sender: 'me', text: 'See you then!'),
      Message(
          sender: 'friend', text: 'I’m running a bit late, be there in 10.'),
      Message(sender: 'me', text: 'No worries, take your time.'),
      Message(sender: 'friend', text: 'Thanks for understanding.'),
      Message(sender: 'me', text: 'Of course, safety first.'),
      Message(sender: 'friend', text: 'Just arrived, where are you?'),
      Message(sender: 'me', text: 'I’m at the entrance.'),
      Message(sender: 'friend', text: 'Got it, heading your way.'),
      Message(sender: 'me', text: 'Great, see you in a sec.'),
      Message(sender: 'friend', text: 'This place looks amazing!'),
      Message(sender: 'me', text: 'It really does, let’s go in.'),
    ],
  ),
  'Design Team': ChatHistory(
    aboutYou: "We bring creative ideas to life through teamwork!",
    messages: [
      Message(sender: 'friend', text: 'New project updates available...'),
      Message(sender: 'me', text: 'Thanks, I’ll review them shortly.'),
      Message(sender: 'friend', text: 'Let us know if you have feedback.'),
      Message(sender: 'me', text: 'Will do, thanks for the heads up.'),
      Message(sender: 'friend', text: 'We have a meeting at 3 PM.'),
      Message(sender: 'me', text: 'Got it, I’ll be there.'),
      Message(sender: 'friend', text: 'Great, see you then.'),
      Message(sender: 'me', text: 'Do we have an agenda?'),
      Message(sender: 'friend', text: 'Yes, I’ll share it with you.'),
      Message(sender: 'me', text: 'Thanks, looking forward to it.'),
      Message(sender: 'friend', text: 'Meeting postponed to 4 PM.'),
      Message(sender: 'me', text: 'Noted, thanks for the update.'),
      Message(sender: 'friend', text: 'No problem, see you then.'),
      Message(sender: 'me', text: 'Do we need to prepare anything?'),
      Message(sender: 'friend', text: 'Just bring your ideas.'),
      Message(sender: 'me', text: 'Got it, will do.'),
      Message(sender: 'friend', text: 'Great, see you at 4.'),
      Message(sender: 'me', text: 'See you then!'),
      Message(sender: 'friend', text: 'Meeting starting now.'),
      Message(sender: 'me', text: 'Joining now.'),
    ],
  ),
  'John Smith': ChatHistory(
    aboutYou: "Always up for a good chat and catching up on life.",
    messages: [
      Message(sender: 'friend', text: 'Thanks for the help!'),
      Message(sender: 'me', text: 'Anytime, happy to help.'),
      Message(sender: 'friend', text: 'Let’s catch up soon.'),
      Message(sender: 'me', text: 'Definitely, how about this weekend?'),
      Message(sender: 'friend', text: 'Sounds good, what day works for you?'),
      Message(sender: 'me', text: 'Saturday afternoon?'),
      Message(sender: 'friend', text: 'Perfect, let’s do it.'),
      Message(sender: 'me', text: 'Great, see you then.'),
      Message(sender: 'friend', text: 'Looking forward to it.'),
      Message(sender: 'me', text: 'Same here!'),
      Message(sender: 'friend', text: 'Do you want to grab lunch?'),
      Message(sender: 'me', text: 'Sure, where do you want to go?'),
      Message(sender: 'friend', text: 'How about that new sushi place?'),
      Message(sender: 'me', text: 'Sounds great, let’s do it.'),
      Message(sender: 'friend', text: 'Great, see you at 12.'),
      Message(sender: 'me', text: 'See you then!'),
      Message(sender: 'friend', text: 'I’m here, where are you?'),
      Message(sender: 'me', text: 'Just parking, be there in a sec.'),
      Message(sender: 'friend', text: 'No rush, take your time.'),
      Message(sender: 'me', text: 'Thanks, see you in a bit.'),
    ],
  ),
  'Emily Davis': ChatHistory(
    aboutYou: "I enjoy sharing cool articles and discoveries!",
    messages: [
      Message(sender: 'friend', text: 'Check out this link!'),
      Message(sender: 'me', text: 'Wow, this is really interesting!'),
      Message(sender: 'friend', text: 'Glad you liked it.'),
      Message(sender: 'me', text: 'Where did you find this?'),
      Message(sender: 'friend', text: 'I came across it on Reddit.'),
      Message(sender: 'me', text: 'Nice find, thanks for sharing.'),
      Message(sender: 'friend', text: 'You’re welcome!'),
      Message(sender: 'me', text: 'Do you have more like this?'),
      Message(sender: 'friend', text: 'Yes, I’ll send you some later.'),
      Message(sender: 'me', text: 'Great, looking forward to it.'),
      Message(sender: 'friend', text: 'Here’s another one.'),
      Message(sender: 'me', text: 'Thanks, this is awesome!'),
      Message(sender: 'friend', text: 'Glad you like it.'),
      Message(sender: 'me', text: 'You have a great eye for this stuff.'),
      Message(sender: 'friend', text: 'Thanks, I try my best.'),
      Message(sender: 'me', text: 'You’re doing great!'),
      Message(sender: 'friend', text: 'Appreciate it!'),
      Message(sender: 'me', text: 'Anytime!'),
      Message(sender: 'friend', text: 'Let me know if you find anything cool.'),
      Message(sender: 'me', text: 'Will do, thanks again!'),
    ],
  ),
  'Marketing Team': ChatHistory(
    aboutYou: "We drive branding and innovative campaigns.",
    messages: [
      Message(sender: 'friend', text: 'Presentation scheduled for tomorrow.'),
      Message(sender: 'me', text: 'Got it. I’ll prepare the slides.'),
      Message(sender: 'friend', text: 'Thanks, let us know if you need help.'),
      Message(sender: 'me', text: 'Will do, thanks for the support.'),
      Message(
          sender: 'friend', text: 'We have a brainstorming session at 2 PM.'),
      Message(sender: 'me', text: 'Noted, I’ll be there.'),
      Message(sender: 'friend', text: 'Great, see you then.'),
      Message(sender: 'me', text: 'Do we have an agenda?'),
      Message(sender: 'friend', text: 'Yes, I’ll share it with you.'),
      Message(sender: 'me', text: 'Thanks, looking forward to it.'),
      Message(sender: 'friend', text: 'Meeting postponed to 3 PM.'),
      Message(sender: 'me', text: 'Noted, thanks for the update.'),
      Message(sender: 'friend', text: 'No problem, see you then.'),
      Message(sender: 'me', text: 'Do we need to prepare anything?'),
      Message(sender: 'friend', text: 'Just bring your ideas.'),
      Message(sender: 'me', text: 'Got it, will do.'),
      Message(sender: 'friend', text: 'Great, see you at 3.'),
      Message(sender: 'me', text: 'See you then!'),
      Message(sender: 'friend', text: 'Meeting starting now.'),
      Message(sender: 'me', text: 'Joining now.'),
    ],
  ),
  'James Brown': ChatHistory(
    aboutYou: "Fitness enthusiast who never skips leg day!",
    messages: [
      Message(sender: 'friend', text: 'See you at the gym.'),
      Message(sender: 'me', text: 'Sure, let’s meet at 6 PM.'),
      Message(sender: 'friend', text: 'Perfect, see you then!'),
      Message(sender: 'me', text: 'Do you want to do cardio or weights?'),
      Message(sender: 'friend', text: 'Let’s do weights today.'),
      Message(sender: 'me', text: 'Sounds good, see you then.'),
      Message(
          sender: 'friend', text: 'I’m running a bit late, be there in 10.'),
      Message(sender: 'me', text: 'No worries, take your time.'),
      Message(sender: 'friend', text: 'Thanks, see you soon.'),
      Message(sender: 'me', text: 'No problem, see you in a bit.'),
      Message(sender: 'friend', text: 'Just arrived, where are you?'),
      Message(sender: 'me', text: 'I’m at the weights section.'),
      Message(sender: 'friend', text: 'Got it, heading your way.'),
      Message(sender: 'me', text: 'Great, see you in a sec.'),
      Message(sender: 'friend', text: 'This place is packed today.'),
      Message(sender: 'me', text: 'Yeah, it’s always busy at this time.'),
      Message(sender: 'friend', text: 'Let’s start with bench press.'),
      Message(sender: 'me', text: 'Sounds good, let’s do it.'),
      Message(sender: 'friend', text: 'Great workout today!'),
      Message(sender: 'me', text: 'Yeah, it was intense!'),
    ],
  ),
  'Chris Taylor': ChatHistory(
    aboutYou: "Detail-oriented and always ready to collaborate!",
    messages: [
      Message(sender: 'friend', text: 'Let me know your thoughts.'),
      Message(sender: 'me', text: 'I’ve shared the document via email.'),
      Message(sender: 'friend', text: 'Got it, I’ll review it soon.'),
      Message(
          sender: 'me', text: 'Thanks, let me know if you have any questions.'),
      Message(sender: 'friend', text: 'Will do, thanks for sending it.'),
      Message(sender: 'me', text: 'No problem, happy to help.'),
      Message(sender: 'friend', text: 'I’ve reviewed the document.'),
      Message(sender: 'me', text: 'Great, what do you think?'),
      Message(
          sender: 'friend', text: 'It looks good, just a few minor changes.'),
      Message(sender: 'me', text: 'Got it, I’ll make the changes.'),
      Message(sender: 'friend', text: 'Thanks, let me know when it’s done.'),
      Message(sender: 'me', text: 'Will do, should be ready soon.'),
      Message(sender: 'friend', text: 'Great, looking forward to it.'),
      Message(sender: 'me', text: 'Changes are done, sending it now.'),
      Message(sender: 'friend', text: 'Got it, thanks a lot!'),
      Message(
          sender: 'me',
          text: 'No problem, let me know if you need anything else.'),
      Message(sender: 'friend', text: 'Will do, thanks again.'),
      Message(sender: 'me', text: 'Anytime!'),
      Message(sender: 'friend', text: 'Let’s catch up soon.'),
      Message(sender: 'me', text: 'Definitely, let’s plan something.'),
    ],
  ),
  'Tech Support': ChatHistory(
    aboutYou: "Helping you solve tech problems, one issue at a time!",
    messages: [
      Message(sender: 'friend', text: 'Your ticket has been resolved.'),
      Message(sender: 'me', text: 'Thanks for the quick response.'),
      Message(sender: 'friend', text: 'Let us know if you face any issues.'),
      Message(sender: 'me', text: 'Will do, thanks again.'),
      Message(sender: 'friend', text: 'No problem, happy to help.'),
      Message(
          sender: 'me', text: 'Do you have any tips to prevent this issue?'),
      Message(sender: 'friend', text: 'Yes, I’ll send you a guide.'),
      Message(sender: 'me', text: 'Great, looking forward to it.'),
      Message(sender: 'friend', text: 'Here’s the guide.'),
      Message(sender: 'me', text: 'Thanks, this is really helpful.'),
      Message(sender: 'friend', text: 'Glad to hear it.'),
      Message(sender: 'me', text: 'Do you offer any training sessions?'),
      Message(sender: 'friend', text: 'Yes, we have a session next week.'),
      Message(sender: 'me', text: 'Great, I’ll sign up for it.'),
      Message(
          sender: 'friend', text: 'Let me know if you need help with that.'),
      Message(sender: 'me', text: 'Will do, thanks again.'),
      Message(sender: 'friend', text: 'No problem, happy to help.'),
      Message(sender: 'me', text: 'You guys are awesome!'),
      Message(sender: 'friend', text: 'Thanks, we try our best.'),
      Message(sender: 'me', text: 'It shows, keep up the great work!'),
    ],
  ),
  'Anna Johnson': ChatHistory(
    aboutYou: "Creative mind stuck on design ideas more often than not!",
    messages: [
      Message(sender: 'friend', text: 'Can we talk now?'),
      Message(sender: 'me', text: 'Sure, give me a call.'),
      Message(sender: 'friend', text: 'Thanks, calling now.'),
      Message(sender: 'me', text: 'Got it, waiting for your call.'),
      Message(sender: 'friend', text: 'I’m having some issues with my phone.'),
      Message(sender: 'me', text: 'No problem, let’s chat here.'),
      Message(sender: 'friend', text: 'Thanks, I appreciate it.'),
      Message(sender: 'me', text: 'No problem, what’s up?'),
      Message(sender: 'friend', text: 'I need some advice on a project.'),
      Message(sender: 'me', text: 'Sure, what do you need help with?'),
      Message(sender: 'friend', text: 'I’m stuck on the design part.'),
      Message(sender: 'me', text: 'I can help with that, let’s discuss.'),
      Message(sender: 'friend', text: 'Great, thanks a lot!'),
      Message(sender: 'me', text: 'No problem, happy to help.'),
      Message(sender: 'friend', text: 'You’re a lifesaver!'),
      Message(sender: 'me', text: 'Glad I can help.'),
      Message(sender: 'friend', text: 'Let’s catch up soon.'),
      Message(sender: 'me', text: 'Definitely, let’s plan something.'),
      Message(sender: 'friend', text: 'Great, looking forward to it.'),
      Message(sender: 'me', text: 'Same here!'),
    ],
  ),
  'David Martinez': ChatHistory(
    aboutYou: "Never forgets birthdays and loves celebrating friends.",
    messages: [
      Message(sender: 'friend', text: 'Happy Birthday!'),
      Message(sender: 'me', text: 'Thank you so much!'),
      Message(sender: 'friend', text: 'Have a great day ahead.'),
      Message(sender: 'me', text: 'Thanks, I’ll try to make the most of it.'),
      Message(sender: 'friend', text: 'Any special plans?'),
      Message(sender: 'me', text: 'Just a quiet dinner with family.'),
      Message(sender: 'friend', text: 'Sounds lovely, enjoy!'),
      Message(sender: 'me', text: 'Thanks, I will!'),
      Message(sender: 'friend', text: 'Let’s catch up soon.'),
      Message(sender: 'me', text: 'Definitely, let’s plan something.'),
      Message(sender: 'friend', text: 'Great, looking forward to it.'),
      Message(sender: 'me', text: 'Same here!'),
      Message(sender: 'friend', text: 'Do you want to grab lunch next week?'),
      Message(sender: 'me', text: 'Sure, what day works for you?'),
      Message(sender: 'friend', text: 'How about Wednesday?'),
      Message(sender: 'me', text: 'Sounds good, let’s do it.'),
      Message(sender: 'friend', text: 'Great, see you then!'),
      Message(sender: 'me', text: 'See you then!'),
      Message(sender: 'friend', text: 'Looking forward to it.'),
      Message(sender: 'me', text: 'Same here!'),
    ],
  ),
  'HR Department': ChatHistory(
    aboutYou: "Ensuring smooth operations and keeping employees informed.",
    messages: [
      Message(sender: 'friend', text: 'Monthly updates shared.'),
      Message(sender: 'me', text: 'I’ve gone through them. Thanks!'),
      Message(sender: 'friend', text: 'Let us know if you have any questions.'),
      Message(sender: 'me', text: 'Will do. Any specific focus areas?'),
      Message(sender: 'friend', text: 'Payroll and compliance updates.'),
      Message(sender: 'me', text: 'Got it. I’ll review those sections.'),
      Message(
          sender: 'friend',
          text: 'Great, let us know if you need clarification.'),
      Message(sender: 'me', text: 'Sure, thanks for the heads-up.'),
      Message(sender: 'friend', text: 'New policies will be shared next week.'),
      Message(sender: 'me', text: 'Looking forward to it.'),
      Message(
          sender: 'friend',
          text: 'Reminder: Training session tomorrow at 10 AM.'),
      Message(sender: 'me', text: 'Noted, I’ll be there.'),
      Message(sender: 'friend', text: 'Great, see you then.'),
      Message(sender: 'me', text: 'Do I need to prepare anything?'),
      Message(sender: 'friend', text: 'Just bring your laptop.'),
      Message(sender: 'me', text: 'Will do. Thanks!'),
      Message(
          sender: 'friend', text: 'Performance reviews are due next Friday.'),
      Message(sender: 'me', text: 'Understood, I’ll submit mine on time.'),
      Message(sender: 'friend', text: 'Appreciate your promptness.'),
      Message(sender: 'me', text: 'No problem, happy to help.'),
    ],
  ),
  'Lisa Moore': ChatHistory(
    aboutYou: "Organized and efficient—let’s keep things on schedule!",
    messages: [
      Message(sender: 'friend', text: 'Meeting rescheduled to 3 PM.'),
      Message(sender: 'me', text: 'Noted, I’ll join on time.'),
      Message(sender: 'friend', text: 'Thanks for confirming.'),
      Message(sender: 'me', text: 'No problem. Is the agenda the same?'),
      Message(
          sender: 'friend', text: 'Yes, we’ll discuss the quarterly report.'),
      Message(sender: 'me', text: 'Got it. I’ll prepare the slides.'),
      Message(sender: 'friend', text: 'Perfect, thanks for taking the lead.'),
      Message(sender: 'me', text: 'My pleasure.'),
      Message(
          sender: 'friend',
          text: 'Can you share the slides before the meeting?'),
      Message(sender: 'me', text: 'Sure, I’ll send them by 2 PM.'),
      Message(sender: 'friend', text: 'Great, that works.'),
      Message(sender: 'me', text: 'Do we need to invite anyone else?'),
      Message(sender: 'friend', text: 'Yes, I’ll add John to the invite.'),
      Message(sender: 'me', text: 'Sounds good.'),
      Message(
          sender: 'friend', text: 'Reminder: Meeting starts in 15 minutes.'),
      Message(sender: 'me', text: 'Joining now.'),
      Message(sender: 'friend', text: 'Great, see you there.'),
      Message(sender: 'me', text: 'Thanks for the reminder.'),
      Message(sender: 'friend', text: 'No problem.'),
      Message(sender: 'me', text: 'Let’s catch up after the meeting.'),
    ],
  ),
  'Adam Scott': ChatHistory(
    aboutYou: "Work hard, but always make time for coffee and friends.",
    messages: [
      Message(sender: 'friend', text: 'Good morning!'),
      Message(sender: 'me', text: 'Morning, how’s it going?'),
      Message(sender: 'friend', text: 'All good, just busy with work.'),
      Message(sender: 'me', text: 'Same here. Anything exciting?'),
      Message(sender: 'friend', text: 'Just wrapping up a project.'),
      Message(sender: 'me', text: 'Nice, how’s it going?'),
      Message(sender: 'friend', text: 'Almost done, just final touches.'),
      Message(sender: 'me', text: 'Great to hear.'),
      Message(sender: 'friend', text: 'What about you?'),
      Message(sender: 'me', text: 'Just planning for next week.'),
      Message(sender: 'friend', text: 'Sounds productive.'),
      Message(sender: 'me', text: 'Trying to be.'),
      Message(sender: 'friend', text: 'Let’s grab coffee soon.'),
      Message(sender: 'me', text: 'Definitely, let’s plan for Friday.'),
      Message(sender: 'friend', text: 'Perfect, see you then.'),
      Message(sender: 'me', text: 'Looking forward to it.'),
      Message(sender: 'friend', text: 'How’s the new project going?'),
      Message(sender: 'me', text: 'It’s going well, just a bit hectic.'),
      Message(sender: 'friend', text: 'I can imagine. Keep it up!'),
      Message(sender: 'me', text: 'Thanks, I’ll try.'),
    ],
  ),
  'Family Group': ChatHistory(
    aboutYou: "Family first, always checking in and planning meetups!",
    messages: [
      Message(sender: 'friend', text: 'Dinner at 7 PM.'),
      Message(sender: 'me', text: 'I’ll be there.'),
      Message(sender: 'friend', text: 'Great, see you soon!'),
      Message(sender: 'me', text: 'What’s on the menu?'),
      Message(sender: 'friend', text: 'Pasta and salad.'),
      Message(sender: 'me', text: 'Sounds delicious.'),
      Message(sender: 'friend', text: 'Can you bring dessert?'),
      Message(sender: 'me', text: 'Sure, I’ll pick up a cake.'),
      Message(sender: 'friend', text: 'Perfect, thanks!'),
      Message(sender: 'me', text: 'No problem.'),
      Message(sender: 'friend', text: 'Don’t forget to bring the board games.'),
      Message(sender: 'me', text: 'Got it, I’ll pack them.'),
      Message(sender: 'friend', text: 'Great, it’s going to be fun.'),
      Message(sender: 'me', text: 'Looking forward to it.'),
      Message(sender: 'friend', text: 'Reminder: Dinner starts in 30 minutes.'),
      Message(sender: 'me', text: 'On my way.'),
      Message(sender: 'friend', text: 'See you soon!'),
      Message(sender: 'me', text: 'Almost there.'),
      Message(sender: 'friend', text: 'We’re waiting for you.'),
      Message(sender: 'me', text: 'Be there in 5.'),
    ],
  ),
  'Sophia Lee': ChatHistory(
    aboutYou: "A perfectionist when it comes to work and presentations.",
    messages: [
      Message(sender: 'friend', text: 'See you soon!'),
      Message(sender: 'me', text: 'Looking forward to it!'),
      Message(sender: 'friend', text: 'Don’t forget to bring the report.'),
      Message(sender: 'me', text: 'I’ve got it ready.'),
      Message(sender: 'friend', text: 'Great, thanks.'),
      Message(sender: 'me', text: 'No problem.'),
      Message(sender: 'friend', text: 'How’s the presentation coming along?'),
      Message(sender: 'me', text: 'Almost done, just polishing it.'),
      Message(sender: 'friend', text: 'Let me know if you need feedback.'),
      Message(sender: 'me', text: 'Will do, thanks.'),
      Message(sender: 'friend', text: 'Reminder: Meeting at 2 PM.'),
      Message(sender: 'me', text: 'Got it, I’ll be there.'),
      Message(sender: 'friend', text: 'Great, see you then.'),
      Message(sender: 'me', text: 'Do we need to prepare anything else?'),
      Message(sender: 'friend', text: 'Just the report and slides.'),
      Message(sender: 'me', text: 'Understood.'),
      Message(sender: 'friend', text: 'Let’s catch up after the meeting.'),
      Message(sender: 'me', text: 'Sounds good.'),
      Message(sender: 'friend', text: 'How’s the new project going?'),
      Message(sender: 'me', text: 'It’s going well, just a bit busy.'),
    ],
  ),
  'Daniel King': ChatHistory(
    aboutYou:
        "Deadlines matter! Let me know if you need help staying on track.",
    messages: [
      Message(sender: 'friend', text: 'Don’t forget the deadline.'),
      Message(sender: 'me', text: 'Thanks, I’ve set a reminder.'),
      Message(sender: 'friend', text: 'Let me know if you need assistance.'),
      Message(sender: 'me', text: 'Will do, thanks for the offer.'),
      Message(sender: 'friend', text: 'How’s the project coming along?'),
      Message(
          sender: 'me', text: 'It’s going well, just a bit behind schedule.'),
      Message(
          sender: 'friend', text: 'Let me know if you need help catching up.'),
      Message(sender: 'me', text: 'Appreciate it, I’ll keep you posted.'),
      Message(sender: 'friend', text: 'Reminder: Deadline is tomorrow.'),
      Message(sender: 'me', text: 'Got it, I’m finalizing everything now.'),
      Message(
          sender: 'friend', text: 'Great, let me know if you need anything.'),
      Message(sender: 'me', text: 'Will do, thanks.'),
      Message(sender: 'friend', text: 'How’s the team doing?'),
      Message(sender: 'me', text: 'They’re doing well, just a bit stressed.'),
      Message(sender: 'friend', text: 'Understandable, it’s a busy time.'),
      Message(sender: 'me', text: 'Yeah, we’ll get through it.'),
      Message(sender: 'friend', text: 'Let’s plan a team lunch after this.'),
      Message(sender: 'me', text: 'Sounds like a great idea.'),
      Message(sender: 'friend', text: 'I’ll send out the invites.'),
      Message(sender: 'me', text: 'Perfect, thanks.'),
    ],
  ),
  'Gaming Buddies': ChatHistory(
    aboutYou: "Gaming marathons and late-night strategies are our thing!",
    messages: [
      Message(sender: 'friend', text: 'Let’s play tonight!'),
      Message(sender: 'me', text: 'Sure, what time works for everyone?'),
      Message(sender: 'friend', text: '9 PM is perfect.'),
      Message(sender: 'me', text: 'Great, I’ll be online.'),
      Message(sender: 'friend', text: 'What game are we playing?'),
      Message(sender: 'me', text: 'How about some Call of Duty?'),
      Message(sender: 'friend', text: 'Sounds good to me.'),
      Message(sender: 'me', text: 'I’ll invite the others.'),
      Message(sender: 'friend', text: 'Great, see you then.'),
      Message(sender: 'me', text: 'Looking forward to it.'),
      Message(sender: 'friend', text: 'Reminder: Gaming session at 9 PM.'),
      Message(sender: 'me', text: 'Got it, I’ll be there.'),
      Message(sender: 'friend', text: 'Let’s make it a long session tonight.'),
      Message(sender: 'me', text: 'I’m in!'),
      Message(sender: 'friend', text: 'How’s your new setup working?'),
      Message(sender: 'me', text: 'It’s amazing, no lag at all.'),
      Message(sender: 'friend', text: 'Great, let’s test it tonight.'),
      Message(sender: 'me', text: 'Can’t wait.'),
      Message(sender: 'friend', text: 'Let’s plan a weekend marathon soon.'),
      Message(sender: 'me', text: 'Sounds like a plan.'),
    ],
  ),
  'Mom': ChatHistory(
    aboutYou:
        "Just making sure you’re eating well and taking care of yourself!",
    messages: [
      Message(sender: 'friend', text: 'Call me when you’re free.'),
      Message(sender: 'me', text: 'Sure, I’ll call after work.'),
      Message(sender: 'friend', text: 'Okay, talk to you then!'),
      Message(sender: 'me', text: 'How’s everything at home?'),
      Message(sender: 'friend', text: 'All good, just missing you.'),
      Message(sender: 'me', text: 'I’ll visit soon.'),
      Message(sender: 'friend', text: 'Looking forward to it.'),
      Message(sender: 'me', text: 'How’s Dad doing?'),
      Message(sender: 'friend', text: 'He’s doing well, just busy with work.'),
      Message(sender: 'me', text: 'Tell him I said hi.'),
      Message(sender: 'friend', text: 'Will do.'),
      Message(sender: 'me', text: 'What’s for dinner tonight?'),
      Message(sender: 'friend', text: 'Your favorite, pasta.'),
      Message(sender: 'me', text: 'Can’t wait to have it.'),
      Message(sender: 'friend', text: 'When are you visiting next?'),
      Message(sender: 'me', text: 'Planning for next weekend.'),
      Message(sender: 'friend', text: 'Great, see you then.'),
      Message(sender: 'me', text: 'Looking forward to it.'),
      Message(sender: 'friend', text: 'Take care of yourself.'),
      Message(sender: 'me', text: 'You too, Mom.'),
    ],
  ),
  'Tom Wilson': ChatHistory(
    aboutYou: "Supportive friend who loves celebrating achievements!",
    messages: [
      Message(sender: 'friend', text: 'Great job on the project!'),
      Message(sender: 'me', text: 'Thank you, glad you liked it.'),
      Message(sender: 'friend', text: 'Let’s celebrate soon.'),
      Message(sender: 'me', text: 'Sounds like a plan.'),
      Message(sender: 'friend', text: 'How about dinner this weekend?'),
      Message(sender: 'me', text: 'I’m in, let’s do it.'),
      Message(sender: 'friend', text: 'Great, I’ll make reservations.'),
      Message(sender: 'me', text: 'Perfect, thanks.'),
      Message(sender: 'friend', text: 'How’s the new role going?'),
      Message(sender: 'me', text: 'It’s going well, just a bit overwhelming.'),
      Message(sender: 'friend', text: 'You’ll get the hang of it soon.'),
      Message(sender: 'me', text: 'Thanks, I hope so.'),
      Message(sender: 'friend', text: 'Let’s catch up more often.'),
      Message(sender: 'me', text: 'Agreed, it’s been too long.'),
      Message(sender: 'friend', text: 'How’s the family doing?'),
      Message(sender: 'me', text: 'They’re doing great, thanks for asking.'),
      Message(sender: 'friend', text: 'Glad to hear it.'),
      Message(sender: 'me', text: 'How about you?'),
      Message(sender: 'friend', text: 'All good here, just busy.'),
      Message(sender: 'me', text: 'Same here, let’s plan something soon.'),
    ],
  ),
  'Rachel Green': ChatHistory(
    aboutYou: "Always taking notes and making sure everyone is prepared!",
    messages: [
      Message(sender: 'friend', text: 'Can you send me the notes?'),
      Message(sender: 'me', text: 'Sure, sharing them now.'),
      Message(sender: 'friend', text: 'Thanks a lot!'),
      Message(sender: 'me', text: 'No problem. Do you need anything else?'),
      Message(sender: 'friend', text: 'Just the notes for now.'),
      Message(sender: 'me', text: 'Got it, let me know if you need more.'),
      Message(sender: 'friend', text: 'Will do, thanks again.'),
      Message(sender: 'me', text: 'Anytime.'),
      Message(sender: 'friend', text: 'How’s the project going?'),
      Message(
          sender: 'me', text: 'It’s going well, just a bit behind schedule.'),
      Message(sender: 'friend', text: 'Let me know if you need help.'),
      Message(sender: 'me', text: 'Appreciate it, I’ll keep you posted.'),
      Message(sender: 'friend', text: 'Reminder: Meeting at 3 PM.'),
      Message(sender: 'me', text: 'Got it, I’ll be there.'),
      Message(sender: 'friend', text: 'Great, see you then.'),
      Message(sender: 'me', text: 'Do we need to prepare anything?'),
      Message(sender: 'friend', text: 'Just the notes and slides.'),
      Message(sender: 'me', text: 'Understood.'),
      Message(sender: 'friend', text: 'Let’s catch up after the meeting.'),
      Message(sender: 'me', text: 'Sounds good.'),
    ],
  ),
};
